# Generated by Django 4.2.4 on 2023-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
